server:
  port: 8081
  
eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Hysterix Service

management:  endpoints:    web:      exposure:        include: hystrix.stream